from pony.orm import db_session
from app import db
from models.Cruise import Cruise
from models.Category import Category
from models.City import City
from models.Ship import Ship

db.drop_all_tables(with_all_data=True)
db.create_tables()

with db_session():



############## ship data

    adventure_of_the_seas = Ship(company='Royal Caribbean', ship='Adventure of the Seas', image='https://images.cruisecritic.com/image/5441/image_1000x_43.jpg', activities='4D Cinema, Casino, Grand Bar with dance floor, Pool deck with retractable glass roofand giant screen, Library, Virtual World, Squok Club, Children’s pool, Theatre on three levels, Disco, Internet Point, Shopping Center')

    allure_of_the_seas = Ship(company='Royal Caribbean', ship='Allure of the Seas', image='https://www.cruisetimetables.com/pictures/allure-of-the-seas-cruise-ship.jpg', activities='Limelight Lounge, FunHub Internet room, Clubhouse and Bar, Thrill Theatre 5D cinema room, Circle C kids club lounge, Club O2 teens club lounge, Warehouse Video Arcade, BlueIguana Tequila Bar poolside Mexican bar')

    anthem_of_the_seas = Ship(company='Royal Caribbean', ship='Anthem of the Seas', image='https://i.ytimg.com/vi/bJk_q50XkG0/maxresdefault.jpg', activities='Living room, The Casino, The Club lounge, Whirlpool, Card Room, 3 duty-free shops, The Coffee Bar, Patio Pool, Sky Bar, The “Spa at Seabourn”, Fitness Center, Observation Bar')

    brilliance_of_the_seas = Ship(company='Royal Caribbean', ship='Brilliance of the Seas', image='https://www.royalcaribbeanblog.com/sites/default/files/blog-images/brilliance-cozumel-dock.jpg', activities='Signature cocktails bar with grand piano, Library, Coffee Connection, Smoking lounge with comfortable leather armchairs; offers hand-rolled Cuban cigars, Card Room / Conference Room, Stars Lounge disco nightclub, The Boutique duty-free shopping arcade, Casino, The Top Deck Power Walking/Jogging Track')

    empress_of_the_seas = Ship(company='Royal Caribbean', ship='Empress of the Seas', image='https://images.cruisecritic.com/image/5613/image_1000x_43.jpg', activities='Boutique and Accessories Shop, Casino, Art Lounge and Bar, Solarium adults-only relaxation area, Main Pool area, Sports and kids facilities, Piano Lounge and Bar, 4D Cinema, F1 car simulator, Flight Simulator')

    explorer_of_the_seas = Ship(company='Royal Caribbean', ship='Explorer of the Seas', image='https://images.cruisecritic.com/image/5442/image_1000x_43.jpg', activities='Buena Vista Theatre, Shutters PhotoShop photographic services, Vista Cafe for specialty coffees and teas, D Lounge Bar & Nightclub, Evolution Disco & Nightclub, Pink adults-only champagne bar, Vibe Disco & Club Lounge teens only, It’s A Small World Nursery, Dream’s Oceaneer Club kids 3-12 years, Senses Spa & Fitness Complex, Frozone Treats, Donald’s Pool, Mickey’s Pool')

    freedom_of_the_seas = Ship(company='Royal Caribbean', ship='Freedom of the Seas', image='https://images.cruisecritic.com/image/5486/image_1000x_43.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    grandeur_of_the_seas = Ship(company='Royal Caribbean', ship='Grandeur of the Seas', image='https://static.businessinsider.sg/2018/12/12/5bf45b5c110d4c21db57e1c4.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    independence_of_the_seas = Ship(company='Royal Caribbean', ship='Independence of the Seas', image='https://www.cruisetimetables.com/pictures/independence-of-the-seas-cruise-ship.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    jewel_of_the_seas = Ship(company='Royal Caribbean', ship='Jewel of the Seas', image='https://images.cruisecritic.com/image/5474/image_1000x_43.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    majesty_of_the_seas = Ship(company='Royal Caribbean', ship='Majesty of the Seas', image='https://www.gannett-cdn.com/-mm-/445af9154db369961cb50860117059dbae6c5558/c=318-0-5298-3744/local/-/media/USATODAY/USATODAY/2014/11/21/635521565641200009-RCI-AerialCocoCay155R.jpg?width=520&height=390&fit=crop', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    oasis_of_the_seas = Ship(company='Royal Caribbean', ship='Oasis of the Seas', image='https://images.cruisecritic.com/image/5491/image_1000x_43.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    ovation_of_the_seas = Ship(company='Royal Caribbean', ship='Ovation of the Seas', image='https://d23n7ahjfnjotp.cloudfront.net/imgs/iphone/ships/new/533_lg.png', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    quantum_of_the_seas = Ship(company='Royal Caribbean', ship='Quantum of the Seas', image='https://d23n7ahjfnjotp.cloudfront.net/imgs/mobileheaderipad/ship_1342438_header_1024x416_mobhdr.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    radiance_of_the_seas = Ship(company='Royal Caribbean', ship='Radiance of the Seas', image='https://www.royalcaribbean.co.uk/assets/images/our-ships/radiance-of-the-seas/homepage/single-image-hero/rccl_singleImageHero.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    rhapsody_of_the_seas = Ship(company='Royal Caribbean', ship='Rhapsody of the Seas', image='https://www.cruisemapper.com/images/ships/661-0a1136bb3baf.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    serenade_of_the_seas = Ship(company='Royal Caribbean', ship='Serenade of the Seas', image='https://s.krfb.de/library/dynamicWidth/standard/aussenansicht.ciw5hg00.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    spectrum_of_the_seas = Ship(company='Royal Caribbean', ship='Spectrum of the Seas', image='https://www.royalcaribbeanblog.com/sites/default/files/blog-images/56791002_2263351220594630_2392947093460221952_o.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

    voyager_of_the_seas = Ship(company='Royal Caribbean', ship='Voyager of the Seas', image='https://images.cruisecritic.com/image/5419/image_1000x_43.jpg', activities='Royal Theater, Indoor ice-skating rink, AquaTheatre pool, Entertainment Place nightclub, The Attic Comedy Club, Jazz Lounge, Art Gallery, Central Park outdoor area with live plants, Casino Royale Card Room, Video Games Arcade, Sports Court, Jogging Track, Rock-climbing Walls')

############# category data

    asia = Category(
    name='Asia',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule1.jpg',
    description_short='You’ll be blown away by incredible Asia. Imagine luxuriating on an idyllic Thai beach or exploring magical gardens in Japan. You’ll adore shopping in Hong Kong’s bustling markets and sampling delicious delicacies in Vietnam. With so many out-of-this-world experiences, it’s one big adventure.'
    )

    australia = Category(
    name='Australia and New Zealand',
    description_short='Feel on top of the world climbing the Sydney Harbour Bridge or be stunned by the jaw-dropping scenery of Milford Sound. Keep an eye out for hobbits at film locations all over New Zealand or visit a Tauranga kiwi orchard. Life down under – you can’t beat it.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule2.jpg',
    )

    bahamas = Category(
    name='Bahamas & Bermuda',
    description_short='You’ll enjoy adventure unlimited in the Bahamas and Bermuda. Explore by kayak or 4x4, discovering rocky outcrops, uninhabited islands and lush interiors. Kids will have the time of their lives – swimming with dolphins, splashing in aquaparks and snorkeling in sparkling seas.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule3.jpg',
    )

    baltic = Category(
    name='Baltic',
    description_short='Be mesmerized by long nights of summer sun, glittering waters off stunning islands and dramatic scenery that takes your breath away. You’ll be captivated by the pleasures of the Baltic, from cool design in Denmark to St. Petersburg’s opulent treasures. It’s truly unmissable.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule4.jpg',
    )

    caribbean = Category(
    name='Caribbean',
    description_short='Relax – you’re in paradise. White sand beaches, cool blue oceans, reggae rhythms drifting on the breeze – what’s the hurry? When you’re ready, explore heady spice plantations, the streets of Havana and cascading waterfalls – every day is laid-back in the fabulous Caribbean.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule5.jpg',
    )

    uk = Category(
    name='Cruises from UK',
    description_short='Say goodbye to holiday hassle with our fabulous cruises from Southampton. Relax from the moment you step onboard, enjoying our extraordinary facilities and amazing choice of restaurants. All while you’ll be sailing to a wide range of fabulous destinations, from Spain’s Canary Islands to Russia’s St. Petersburg. So sit back and enjoy the ride.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule6.jpg',
    )

    europe = Category(
    name='Europe',
    description_short='Get the tick list ready. You’re about to experience those ‘must-see’ places in Europe that you’ve always dreamed of seeing. From Rome’s iconic ruins and Venice’s famous canals to Granada’s Alhambra and Norway’s stunning fjords – the choice is yours.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule7.jpg',
    )

    mediterranean = Category(
    name='Mediterranean',
    description_short='Gasp at gorgeous sea views from Santorini’s stunning cliffs, dotted with white-washed houses that sparkle in the sun. Watch the world go by in a lively waterfront bar or discover hidden gems, such as Montenegro’s spectacular scenery and Croatia’s lively cities. In the Mediterranean, your options are endless.', image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule8.jpg',
    )

    middleeast = Category(
    name='Middle East',
    description_short='Sample Arabic pastries, ride a camel in the desert or shop for falcons in the souk. From glitzy malls to stunning Islamic art, your Middle East holiday will be sensational.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule13.jpg',
    )

    northamerica = Category(name='North America',
    description_short='Imagine deep fjords, icy blue glaciers and untamed snowcaps – Alaska’s natural wilderness is exhilarating in the extreme. Immerse yourself in the buzz of New York or the laid-back vibes of the Florida Keys – no matter what you choose, your holiday to North America will be amazing.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule9.jpg',
    )

    oceanvoyages = Category(
    name='Ocean Voyages',
    description_short='It’s not always about where you end up, but the fun you have getting there. If you love adventures at sea, let us take you onboard. We’ll entertain, pamper, amuse and excite you with our fabulous facilities and amazing entertainment, sharing unforgettable moments along the way.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule10.jpg',
    )

    scandinavia = Category(
    name='Scandinavia',
    description_short='Stand face-to-face with Viking ships or taste world class New Nordic cuisine. You’ll love the buzz of Scandinavia and its creative and youthful vibe. With amazing art, fascinating history and outstanding natural beauty to explore, you’ll be impressed.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule11.jpg',
    )

    southpacific = Category(
    name='South Pacific',
    description_short='Who doesn’t dream of a paradise island in the South Pacific, with swaying palm trees and beaches of pure white sand? There’s a world of wonder beneath too, in the vibrant coral reefs teeming with colourful fish. Grab a snorkel and explore.',
    image='https://www.royalcaribbean.co.uk/assets/images/holiday-destinations/region-module/rccl_regionModule12.jpg',
    )

############# city data

    city1 = City(name='Hong Kong, Chan Ma, Hong Kong')
    city2 = City(name='Sydney, Newcastle, Airlie Beach, Cairns, Darwin, Benoa, Port Hedland, Geraldton, Perth')
    city3 = City(name='Tianjin, Fukuoka, Tianjin')
    city4 = City(name='Singapore, Malacca, Penang, Phuket, Thailand')
    city5 = City(name='Singapore, Laemchabang, Ho Chi Minh (Phu My), Nha Trang, Hue/Danang (Chan May), Hong Kong')
    city6 = City(name='Sydney, Sydney')
    city7 = City(name='Sydney, Noumea, Mystery Island, Bay Of Islands, Sydney')
    city8 = City(name='Sydney, Noumea, Mystery Island, Vila, Lifou, Sydney')
    city9 = City(name='Sydney, Port Arthur, Hobart, Hobart, Sydney')
    city10 = City(name='Fort Lauderdale, Perfect Day CocoCay, Cozumel, Fort Lauderdale')
    city11 = City(name='Fort Lauderdale, Labadee, Nassau, Fort Lauderdale')
    city12 = City(name='Fort Lauderdale, Key West, Nassau, Fort Lauderdale')
    city13 = City(name='Tampa, Kings Wharf, Ponta Delgada, Málaga, Alicante, Barcelona')
    city14 = City(name='Cape Liberty, Kings Wharf, Kings Wharf, Cape Liberty')
    city15 = City(name='Copenhagen, Geiranger, Arctic Circle,Tromso, Honningsvåg, Alesund, Flâm, Stavanger, Copenhagen')
    city16 = City(name='Stockholm, Stockholm, Helsinki, St. Petersburg, St. Petersburg, St. Petersburg, Tallinn, Riga, Visby, Berlin, Fredericia, Copenhagen, Copenhagen')
    city17 = City(name='Amsterdam, Skagen, Tallinn, St. Petersburg, St. Petersburg, Helsinki, Stockholm, Copenhagen, Amsterdam')
    city18 = City(name='Southampton, Bruges, Oslo, Hamburg, Paris/Normandy, Southampton')
    city19 = City(name='San Juan, Oranjestad, Willemstad, Kralendijk, Philipsburg, San Juan')
    city20 = City(name="San Juan, St. John's, Castries, Bridgetown, San Juan")
    city21 = City(name='Miami, George Town, Cienfuegos, Havana, Miami')
    city22 = City(name='Miami, Philipsburg, San Juan, Labadee, Miami')
    city23 = City(name="San Juan, Bridgetown, St. George's, Roseau, Philipsburg, Charlotte Amalie, San Juan")
    city24 = City(name="Baltimore, St. Croix, Philipsburg, Castries, Bridgetown, Basseterre, Baltimore")
    city25 = City(name='Southampton, La Coruña, Madeira, Tenerife, Gran Canaria, Lisbon, Vigo, Southampton')
    city26 = City(name='Shanghai, Vladivostok, Kyoto, Fukuoka, Shanghai')
    city27 = City(name='Southampton, Gibraltar, Alicante, Barcelona, Marseille, Lisbon, Cherbourg, Southampton')
    city28 = City(name='Barcelona, Nice, Portofino, Florence/Pisa, Rome, Amalfi Coast, Barcelona')
    city29 = City(name='Copenhagen, Berlin, Tallinn, St. Petersburg, St. Petersburg, Helsinki, Visby, Riga, Stockholm, Stockholm')
    city30 = City(name='Rome, Messina, Valletta, Mykonos, Kusadasi, Santorini, Athens, Naples, Rome')
    city31 = City(name='Southampton, Ponta Delgada, Madeira, Gran Canaria, Tenerife, Lanzarote, Lisbon, Southampton')
    city32 = City(name='Fort Lauderdale, Málaga, Barcelona')
    city33 = City(name='Rome, Messina, Athens, Santorini, Suez Canal, Suez Canal, Aqaba, Muscat, Dubai, Dubai')
    city34 = City(name='Barcelona, Kotor, Zadar, Venice, Venice, Naples, Rome, Florence/Pisa, Marseille, Barcelona')
    city35 = City(name='Southampton, Paris/Normandy, Bilbao, Southampton')
    city36 = City(name='Venice, Kotor, Dubrovnik, Santorini, Katakolon')
    city37 = City(name='Rome, Naples, Valencia, Barcelona, Provence, Florence/Pisa, Rome')
    city38 = City(name='Dubai, Doha, Bahrain, Sir Bani Yas, Abu Dhabi, Dubai, Dubai')
    city39 = City(name='Dubai, Dubai, Bahrain, Doha, Sir Bani Yas, Khasab, Muscat, Abu Dhabi')
    city40 = City(name='Dubai, Dubai, Bahrain, Doha, Sir Bani Yas, Khasab, Muscat, Abu Dhabi, Dubai')
    city41 = City(name='Dubai, Dubai, Abu Dhabi, Sir Bani Yas, Oman Dubai, Dubai')
    city42 = City(name='Vancouver, Ketchikan, Vancouver')
    city43 = City(name='Cape Liberty, Bar Harbor, Saint John, Halifax, Cape Liberty')
    city44 = City(name='Honolulu, Lahaina, Kailua Kona, Hilo, Kauai, Vancouver')
    city45 = City(name='Southampton, Bergen, Flâm, Geiranger, Alesund, Stavanger, Southampton')
    city46 = City(name='Sydney, Isle of Pines, Mystery Island, Vila, Suva, Lautoka, Sydney')
    city47 = City(name='Honolulu, Papeete, Moorea, Bora Bora, Auckland, Bay of Islands, Sydney')
    city48 = City(name='Brisbane, Noumea, Lifou, Vila, Mystery Island, Brisbane')
    city49 = City(name='Brisbane, Isle of Pines, Mystery Island, Vila, Brisbane')
    city50 = City(name='Brisbane, Mystery Island, Luganville, Vila, Noumea, Brisbane')
    # Denmark
    # finland
    # sweden


############# cruise data

    cruiseone = Cruise(name='Best Of Chan May', region='China', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/1093.jpg', description_short="From Hong Kong's exhilarating markets to Shanghai's famous Bund and the awe-inspiring Forbidden City in Beijing, you'll be blown away by our amazing Asia holidays to China. Mouth-watering cuisine, superb shopping, iconic sights - it's your adventure of a lifetime.", description_long='Hang out at beautiful China Beach, where American soldiers used to go for rest and recreation during the Vietnam War. Discover the delicious street food in downtown Da Nang or the wonders of Hu?, on the Perfume River, the former seat of the Nguyen Dynasty. Its 19th century Citadel protected the Imperial City, with its opulent palaces and shrines, including the Forbidden Purple City, once the home of emperors.', categories=[asia], ship=voyager_of_the_seas)

    cruisetwo = Cruise(name='Indonesia Top End', region='Indonesia', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808103929839_550X270.jpg', description_short="Experience a warm Indonesian welcome in beautiful Bali, where you'll find stunning temples, idyllic beaches and mouth-watering cuisine. How about trying Balinese dance, shopping for jewellery or going on a thrilling elephant safari", description_long='ndulge your senses with the sights, sounds and smells of this exquisite island paradise, with its lush tropical vegetation, exotic flowers, imposing temples and idyllic beaches. Enjoy the warmth of Bali’s people and their mouth-watering cuisine. Explore the black coral temple of Pura Luhur Uluwatu, the Sacred Forest Monkey Sanctuary at Ubud or go on an elephant safari. For thrills try white water rafting.', categories=[asia, southpacific], ship=serenade_of_the_seas)

    cruisethree = Cruise(name='Best Of Fukuoka', region='Japan', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808104035822_550X270.jpg', description_short="Enchanting Japan will inspire you. Enjoy mouth-watering delicacies in Kochi's exotic markets, relax in a sensuous hot spa or explore Fukuoka's fascinating temples, shrines and museums. In Nagasaki, you can even cross swords with the Samurai.", description_long='The state of Hawaii derives its name from the name of its largest island, Hawaiʻi. The legendary figure from Hawaiian myth. He is said to have discovered the islands when they were first settled.', categories=[asia], ship=quantum_of_the_seas)

    cruisefour = Cruise(name='Spice Of Southeast Asia', region='Singapore', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/1695.jpg', description_short="Wow! You'll be blown away by the space-age bio-domes of Gardens by the Bay, Singapore's stunning waterfront park. Let yourself be tempted by the mouth-watering cuisine of Singapore's many cultures and explore its lively markets and beautiful beaches.", description_long="Taste Singapore’s mouth-watering cuisine, influenced by the flavours of Malaysia, China and India. Visit the stunning Botanic Gardens and National Orchid Garden or the exotic Jurong Bird Park to see colourful toucans, pelicans, eagles and parrots. Take a ferry to the islands for unspoilt beaches or enjoy south-east Asian art at the National Gallery. A temple in Singapore’s Chinatown is said to house one of the Buddha's teeth.", categories=[asia], ship=voyager_of_the_seas)

    cruisefive = Cruise(name='Thailand & Vietnam', region='Thailand', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808104625094_550X270.jpg', description_short="Discover the thrills of tantalising Thailand. Enjoy stunning beaches and amazing watersports in idyllic Phuket or explore exhilarating Bangkok, with its floating markets, out-of-this-world street food and awe-inspiring temples.", description_long="Ride an elephant in the Pattaya Elephant Village or marvel at the huge jade Emerald Buddha at Wat Phra Kaew Temple in Bangkok's Grand Palace. Sample pad thai, coconut pancakes and other Thai delights in the atmospheric Pattaya Floating Market or be wow’ed by the awe-inspiring Wat Arun temple. The bustling gold shops, neon lights and market stalls of Bangkok Chinatown are also an unforgettable experience.", categories=[asia], ship=quantum_of_the_seas)

    cruisesix = Cruise(name='3 Night Sampler', region='Australia', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/1219.jpg', description_short="Experience amazing adventures on your unforgettable holiday to Australia. You'll love Brisbane's Gold Coast scenery and Sydney's stunning Opera House. Explore Darwin and Cairns for crocs and corals and don't miss the buzzing cultural scene of Melbourne and Adelaide.", description_long="Take in spectacular views from the Sydney Tower’s outdoor platform, the Skywalk. Visit the iconic Sydney Opera House for a behind-the-scenes tour, climb the Harbour Bridge or people watch at Bondi Beach. Sample the fabulous restaurants at Circular Quay or Darling Harbour or hit the shops at the Queen Victoria Building or the Westfield and Pitt Street malls. Enjoy art, culture and outdoor adventures too in this vibrant city.", categories=[australia], ship=radiance_of_the_seas)

    cruiseseven = Cruise(name='10 nights New Zealand', region='New Zealand', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/2375.jpg', description_short="Prepare to be blown away by beautiful New Zealand. There are fascinating destinations to explore, from the stunning volcanic scenery of Auckland to Milford Sound's majestic fjords. Don't miss Wellington's restaurants, Akaroa's marine life and the Hobbiton Movie set used for Lord of the Rings.", description_long="Taste your way around tempting Wellington, known for its brilliant bars and restaurants, craft beers, coffee shops and delicious wines. Or take a picnic up to Mount Victoria Lookout for stunning panoramic views of the city and beyond. Ride the historic cable car for more spectacular sights and visit the Wellington Botanic Garden along the way. A thriving arts scene and designer boutiques add to the city’s delights.", categories=[australia], ship=serenade_of_the_seas)

    cruiseeight = Cruise(name='South Pacific & New Zealand', region='New Zealand', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/1739_embed.jpg', description_short="Prepare to be blown away by beautiful New Zealand. There are fascinating destinations to explore, from the stunning volcanic scenery of Auckland to Milford Sound's majestic fjords. Don't miss Wellington's restaurants, Akaroa's marine life and the Hobbiton Movie set used for Lord of the Rings.", description_long="140 subtropical islands make up the beautiful Bay of Islands in New Zealand’s North Island. Discover fascinating Maori culture, explore the area’s whaling and colonial past, spot dolphins and penguins or enjoy adventures such as kayaking, mountain-biking, parasailing and scuba-diving in this stunning region. Sail to the Hole in the Rock at Piercy Island and hear stories about Captain Cook.", categories=[australia], ship=ovation_of_the_seas)

    cruisenine = Cruise(name='Tasmania', region='Australia', image='https://www.royalcaribbean.co.uk/images/PortImages/HBA_20160831092913783_258X162.jpg', description_short="Experience amazing adventures on your unforgettable holiday to Australia. You'll love Brisbane's Gold Coast scenery and Sydney's stunning Opera House. Explore Darwin and Cairns for crocs and corals and don't miss the buzzing cultural scene of Melbourne and Adelaide.", description_long="Meet the rescued Tasmanian Devils and Bettongs at the Bonorong Wildlife Sanctuary or see towering sequoia trees and stunning orchids in the Royal Tasmanian Botanical Gardens. Take a tipple of delicious wine at the acclaimed Moorilla Winery or discover the vibrant bars and restaurants at Salamanca Place. The edgy Museum of Old and New Art has some thought-provoking collections.", categories=[australia], ship=voyager_of_the_seas)

    cruiseten = Cruise(name='Western Caribbean & Perfect Day', region='Bahamas', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/2444_embed.jpg', description_short="You're in paradise in idyllic Cococay, in the sun-kissed Bahamas. Try parasailing, jet skiing or snorkelling in this private resort or relax to the sound of steel drums. You'll find more beautiful beaches in stunning Nassau or Grand Bahama, plus tantalising shopping.", description_long="Be one of the brave first to conquer the tallest waterslide in North America and snap a shot from 400 feet up in a helium balloon. Grab a drink at the swim-up bar and soak up the scene in the largest freshwater pool in the Bahamas. Or get a taste of Bora Bora with your own overwater cabana. This is perfection created for you. This is Perfect Day at CocoCay — only on Royal Caribbean®.", categories=[bahamas], ship=majesty_of_the_seas)

    cruiseeleven = Cruise(name='Western Caribbean', region='Bahamas', image='https://www.royalcaribbean.co.uk/images/PortImages/NAS_20160831092914095_258X162.jpg', description_short="You're in paradise in idyllic Cococay, in the sun-kissed Bahamas. Try parasailing, jet skiing or snorkelling in this private resort or relax to the sound of steel drums. You'll find more beautiful beaches in stunning Nassau or Grand Bahama, plus tantalising shopping.", description_long="Snorkelling in clear blue lagoons, swimming with dolphins, watery fun and games in an aqua adventure park – there’s plenty to enjoy in stunning Nassau. Relax to the sweet sound of the steel drums, sip a cocktail at sunset or see baby sea turtles being hatched. At Predator Lagoon, get up close to sharks and barracudas or indulge in tantalising shopping – it’s what dream holidays are all about.", categories=[bahamas], ship=majesty_of_the_seas)

    cruisetwelve = Cruise(name='Key West & Nassau', region='Bahamas', image='https://www.royalcaribbean.co.uk/images/PortImages/EYW_20160831092913626_258X162.jpg', description_short="You're in paradise in idyllic Cococay, in the sun-kissed Bahamas. Try parasailing, jet skiing or snorkelling in this private resort or relax to the sound of steel drums. You'll find more beautiful beaches in stunning Nassau or Grand Bahama, plus tantalising shopping.", description_long="Explore art treasures in the galleries and museums or paddle a glass-bottomed kayak among the mangroves and marine life. Try delicious sea food and key lime pie or watch inventive street performers at work.", categories=[bahamas], ship=majesty_of_the_seas)

    cruisethirteen = Cruise(name='14 night Bermuda & Spain Crossing', region='Bermuda', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/2207.jpg', description_short="Explore Bermuda's stunning coastline by boat, sipping delicious rum along the way. You can search for shipwrecks in the Bermuda Triangle or tour the island's idyllic beaches and beautiful nature reserves. Shopaholic? Then spoil yourself in the tempting shops at lively King's Wharf.", description_long="Rum tasting is a must on a cruise around the gorgeous island of Bermuda. Search for shipwrecks in the Bermuda Triangle or see awe-inspiring limestone formations in the spectacular crystal caves. At King’s Wharf, tour the Maritime Museum, opt for an encounter with dolphins or shop for porcelain, crystal and local goods. Further afield explore Bermuda’s idyllic beaches, turquoise seas and beautiful nature reserves.", categories=[bahamas], ship=rhapsody_of_the_seas)

    cruisefourteen = Cruise(name='Bermuda', region='Bermuda', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/145.jpg', description_short="Explore Bermuda's stunning coastline by boat, sipping delicious rum along the way. You can search for shipwrecks in the Bermuda Triangle or tour the island's idyllic beaches and beautiful nature reserves. Shopaholic? Then spoil yourself in the tempting shops at lively King's Wharf.", description_long="The Farmers’ Market is foodie heaven, along with the city’s cool restaurants, bars and breweries.", categories=[bahamas], ship=grandeur_of_the_seas)

    cruisefifteen = Cruise(name='11 night Arctic Circle', region='Denmark', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719103221961_550X270.jpg', description_short="Discover fascinating history, cutting-edge design and breath-taking natural beauty on your unforgettable cruise to the Baltic. You’ll be captivated by the light on the long summer evenings, which gives way to open-air festivities and fun.", description_long="Have fun in laid-back Denmark, where a relaxed approach is combined with creativity and style. From cool Copenhagen, with its avant-garde bars and restaurants and historic landmarks, to outdoor pleasures in idyllic Jutland, you'll be hooked.", categories=[baltic, scandinavia], ship=serenade_of_the_seas)

    cruisesixteen = Cruise(name='Ultimate Scandinavia-Russia', region='Finland', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719112252492_550X270.jpg', description_short="The scenery is stunning, from the archipelagoes of Stockholm and Helsinki to Denmark’s lovely beaches. And for history buffs there are the glittering palaces of St. Petersburg, Poland’s pivotal past and the area’s Soviet-era and Second World War landmarks.", description_long="Discover a taste of Finland with dishes of reindeer, herring and cloudberries. Be blown away by Helsinki's stunning archipelago, where granite islands sit in sparkling seas. The city's Market Square, Temppeliaukio church and Olympic stadium are not to be missed.", categories=[baltic, scandinavia], ship=serenade_of_the_seas)

    cruiseseventeen = Cruise(name='12 night Baltic', region='Sweden', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170720053908529_550X270.jpg', description_short="Be impressed by the beauty of Stockholm’s stunning archipelago, say Skol! in an ice bar or visit the magnificent City Hall. Be wow’ed by the breath-taking Vasa, the best preserved and most complete 17th century ship in the world, which sank in the city’s waters in 1628. A coffee and a pastry is an essential Swedish tradition and a tour of the winding streets of medieval Gamla Stan is a delight.", description_long="You're surrounded by stunning natural beauty in Sweden and in summer there's endless daylight. Be tempted by the boutiques, cafes and restaurants of Stockholm's atmospheric old town and visit the amazing Vasa - a 17th century warship rescued from the depths of the sea.", categories=[baltic, scandinavia], ship=brilliance_of_the_seas)

    cruiseeighteen = Cruise(name='Northern Europe Cities', region='Germany', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808070819088_550X270.jpg', description_short="German cities fizz with life, from bohemian Berlin to Hamburg's lively bars, restaurants and beer cellars. You'll be fascinated by the clubs and cultural scene of Berlin as well as its unmissable landmarks, such as the Brandenburg Gate, the Reichstag and Checkpoint Charlie.", description_long="Swimming, sailing, kayaking and boat trips feature high in the life of Hamburg, surrounded by the waters of the River Elbe and the Alster Lake. With a youthful vibe, the city’s bars, clubs and restaurants come alive at night and the atmospheric beer cellars are not to be missed. Explore fascinating museums and art galleries, such as Miniatur Wunderland, the largest model railway system in the world, with 930 trains.", categories=[baltic], ship=anthem_of_the_seas)

    cruisenineteen = Cruise(name='Southern Caribbean', region='Aruba', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808072820963_550X270.jpg', description_short="Picture yourself on beautiful stretches of pure white sand, beside turquoise waters filled with tropical fish, listening to calypso rhythms under sun-soaked skies. Round off the day with a rum punch on the beach, taking in the breath-taking views.", description_long="Palm-fringed beaches and shimmering seas make the Dutch Caribbean island of Aruba a beach lover's paradise. Why not kite surf over the sands, plunge in the cooling Natural Pool in the Arikok National Park or watch stunning sunsets from an Oranjestad beachfront bar?", categories=[caribbean], ship=freedom_of_the_seas)

    cruisetwenty = Cruise(name='Southern Caribbean', region='Barbados', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808073300768_550X270.jpg', description_short="Are you open to adventure? Why not ride a rainforest riverboat in Belize, dive with turtles in Barbados, sample Creole cuisine in St. Maarten or plunge into a hot spring in St. Lucia – it’s all about you on your Caribbean dream holiday. With so many exciting destinations to explore on one holiday, what are you waiting for? Your private paradise awaits.", description_long="Sway to the calypso in a beach bar, parasail above emerald seas or snorkel amongst shipwrecks and sea turtles. Explore Bridgetown's 17th century colonial architecture or its Jewish history. You'll feel at home in beautiful Barbados, where paradise comes with a smile.", categories=[caribbean], ship=grandeur_of_the_seas)

    cruisetwentyone = Cruise(name='Best Of Cuba', region='Grand Cayman', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808074044303_550X270.jpg', description_short="Say hello to stingrays and sea turtles in stunning Grand Cayman and enjoy snorkelling among the dazzling tropical fish. Will it be luxuriating on a white sand beach or duty-free shopping in George Town? Or why not both?", description_long="Snorkel among tropical fish and colourful coral at Coral Gardens Reef or get up close to amazing stingrays. Parasail above the clear blue waters and glistening sands or see shipwrecks and spectacular marine life from a glass bottomed boat. Encounter endangered Green Sea Turtles at the Cayman Turtle Farm or send a postcard home from Hell, a striking outcrop of black limestone in West Bay", categories=[caribbean], ship=empress_of_the_seas)

    cruisetwentytwo = Cruise(name='Eastern Caribbean', region='St. Maarten', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20171213132622757_550X270.jpg', description_short="Sail or snorkel in dazzling waters on this welcoming and sun-kissed island, settled by the Dutch and the French. Browse the markets and tempting duty-free shops in Philipsburg, the Dutch capital, or chill with the locals in the laid-back cafes and restaurants.", description_long="Let your hair down to a steel band, sail or snorkel in dazzling waters or soak up the sun on this welcoming island, settled by the Dutch and the French. Browse the markets and tempting duty-free shops in Philipsburg, the Dutch capital, or chill with the friendly locals in the laid-back cafes and restaurants. With fabulous white sandy beaches and crystal clear seas, it’s a Caribbean dream.", categories=[caribbean], ship=allure_of_the_seas)

    cruisetwentythree = Cruise(name='Southern Caribbean Holiday', region='Mexico', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808075214004_550X270.jpg', description_short="Drive your own mini submarine, snorkel on world famous reefs or see the colourful underwater world by glass bottomed boat in lovely Cozumel, on the Caribbean coast of Mexico. There are fascinating Mayan ruins to explore too and abundant wildlife, including brightly-hued tropical birds. Look out for dolphins, manatees and sea turtles in the lovely lagoon and underwater caverns of the Chankanaab eco-park.", description_long="Swim, sail and scuba dive in the sparkling seas and translucent lagoons of Puerto Costa Maya. Channel your inner explorer on a jungle adventure, spotting toucans, spider monkeys and iguanas along the way. You'll love the fascinating Mayan ruins in Cozumel and the Yucatan.", categories=[caribbean], ship=serenade_of_the_seas)

    cruisetwentyfour = Cruise(name='Southern Caribbean', region='U.S. Virgin Islands', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808091530344_550X270.jpg', description_short="Why resist? Indulge in duty-free shopping and mouth-watering food on utopian St. Croix, or get your heart pumping with scuba diving, a horse ride, a round of golf or game fishing. With such a beautiful island to explore, fun is what it's all about.", description_long="Sail around idyllic St Lucia or tour its towering mountains, banana plantations, valleys and rainforest by bus or 4x4. Take a trip to historic Soufrière to view the dramatic Pitons, volcanic plugs that dominate the island, or bathe in hot mineral springs at the Diamond Falls Botanical Gardens. For adventure lovers, the Adrena-Line rainforest adventure course and a paintball challenge will get your heart pumping.", categories=[caribbean], ship=grandeur_of_the_seas)

    cruisetwentyfive = Cruise(name='Canaries Adventure', region='Portugal', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170720053346866_550X270.jpg', description_short="Discover Portugal's mouth-watering specialities, from salted cod, chourico and custard tarts to port, vinho verde and douro wines. You'll love the beaches, boulevards and café culture of Lisbon and in Madeira you can enjoy exhilarating toboggan and cable car rides.", description_long="Take a thrilling toboggan ride from Monte to Funchal or glide round the stunning coastline on the replica of a ship sailed by Christopher Columbus. Scenic cable cars are a great way to see the breath-taking sights of this lush and mountainous island and the exotic plants of the Madeira Botanical Garden are a gardeners’ delight. For adventure, abseil the island’s canyons or go on an exciting jeep ride.", categories=[uk], ship=independence_of_the_seas)

    cruisetwentysix = Cruise(name='Russia & Japan', region='Russia', image='https://www.royalcaribbean.co.uk/images/PortImages/VVO_20180615114646119_258X162.jpg', description_short="Be blown away by the holiday of a lifetime to Russia. In stunning St. Petersburg you can enjoy world-class ballet, Russian folklore and vodka tasting. The dazzling opulence of the Hermitage, Peterhof Palace and St. Isaac's Cathedral will take your breath away.", description_long="Explore the impressive forts and secret Soviet-era tunnels in Vladivostok, a Russian Pacific port in the Far East. Snap the stunning views over Golden Horn Bay or the lovely Cathedral of the Intercession. Watch the Mariinsky ballet at the Primorsky Stage, feel the creative buzz at the Zarya Centre for Contemporary Art or tour the Hermitage Vladivostok. To take in the sights, cycle on Tsesarevich Embankment.", categories=[uk], ship=spectrum_of_the_seas)

    cruisetwentyseven = Cruise(name='Mediterranean Tour', region='Gibraltar', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719112630627_550X270.jpg', description_short="Experience life on top of the world on Gibraltar's famous Rock, at the meeting of the Atlantic Ocean and Mediterranean Sea. Meet the Barbary macaques, hit the duty free shops, take a thrilling cable car ride or see amazing rock formations in St. Michael's Cave.", description_long="Experience the thrill of hiking to the summit of Gibraltar’s famous Rock and being rewarded with spectacular views. Wonder at the stalactites and stalagmites in St Michael’s Cave or sail off in search of dolphins. For a more relaxing break take the cable car to the mountain top, discover local history in the Gibraltar Museum or sample tempting tapas and wines. For some serious indulgence, hit the duty-free shops.", categories=[uk], ship=explorer_of_the_seas)

    cruisetwentyeight = Cruise(name='Mediterranean', region='Italy', image='https://www.royalcaribbean.co.uk/images/PortImages/SNO_20160831092914439_258X162.jpg', description_short="Impeccable style, divine cuisine, exquisite architecture - you'll be captivated by unmissable Italy. Explore the stunning art treasures of Florence, the romantic canals of Venice, the glorious monuments of Rome and Sicily's sizzling volcano - unforgettable.", description_long="Cruise the breath-taking Amalfi coastline, taste sun-drenched locally-made Limoncello or jet off to the glamourous Isle of Capri. Evocative Pompeii will tug at your heart strings while Sorrento’s stunning clifftop location over the Bay of Naples will leave you lost for words. For the fearless, there’s an energetic hike to the summit of Mount Vesuvius, the active volcano that wreaked so much havoc in 79 AD.", categories=[uk], ship=brilliance_of_the_seas)

    cruisetwentynine = Cruise(name='Ultimate Scandinavia & Russia', region='Latvia', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719114326711_550X270.jpg', description_short="Lovely Latvia will surprise you. Enjoy trekking and cycling among beautiful beaches, forests and lakes or explore bustling Riga with its chic restaurants and impressive architecture. Treat yourself to some amber jewellery or a thrilling bobsleigh ride.", description_long="Cosmopolitan Riga buzzes with youthful excitement and verve but is also known for its architectural gems, including a 13th-century cathedral, wooden houses and Art Nouveau buildings. See the city by canal boat or try Riga’s chic restaurants with their fusion of traditional and avant-garde cuisine. Breathe fresh air on walks or cycle rides in the nature parks, beaches and woods or indulge in a heavenly spa treatment.", categories=[europe], ship=jewel_of_the_seas)

    cruisethirty = Cruise(name='Greek Isles', region='Malta', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719114536363_550X270.jpg', description_short="You'll find fascinating history in Malta, once ruled by the Romans, Moors and Knights of Saint John. But there's lots more too. Snorkel in azure waters, tour amazing underground burial chambers or treat yourself to souvenirs and silver in Valletta's tempting shops.", description_long="Be inspired by Valletta’s Baroque palaces, impressive churches and beautiful gardens. Be blown away by the iridescent colours of the cliffside caves at the Blue Grotto or experience the unforgettable thrill of swimming with dolphins. Packed with history, Valletta’s St John’s Co-Cathedral and the Grandmaster’s Palace are a must for culture buffs. Action-lovers can explore the island’s treasures by boat or Segway.", categories=[europe], ship=explorer_of_the_seas)

    cruisethirtyone = Cruise(name='Canaries & Azores', region='Canary Islands', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719100141368_550X270.jpg', description_short="Soak up the sun-kissed splendour of the Canary Islands, where spectacular sea, sand and scenery combine. From watersports in Gran Canaria and the orchids of Tenerife to the extraordinary volcanic landscapes of Lanzarote, you'll find holiday heaven.", description_long="Soak up the sun on the gorgeous beaches of Las Palmas, where golden sands, safe swimming, surfing and water sports are there to be enjoyed. Hit the tempting shops, cafes and restaurants in this bustling city, savouring delicious Canarian food with its Spanish, Latin American and African influences. If you’re lucky, catch one of Gran Canaria’s vibrant fiestas or delve into the city’s lively nightlife.", categories=[europe], ship=explorer_of_the_seas)

    cruisethirtytwo = Cruise(name='Spanish Transatlantic', region='Spain', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170720053720376_550X270.jpg', description_short="Experience the magic of vibrant Spain, with its fiery flamenco, popular promenades, fun fiestas and tempting tapas bars. Don't miss Mallorca's stylish beaches, Granada's awe-inspiring Alhambra, Bilbao's stunning Guggenheim or the irresistible buzz of Barcelona.", description_long="See and be seen in bustling Las Ramblas, where the shops and street performers will catch your eye. Enjoy the colourful creations of celebrated architect Antoni Gaudi, including La Sagrada Familia, Casa Vicens and Parc Guell. Take a trip to Camp Nou, the home of FC Barcelona or jog, cycle or stroll on the city’s fine beaches. For pleasure seekers, there’s thriving nightlife and brilliant dining in Barcelona too.", categories=[europe], ship=allure_of_the_seas)

    cruisethirtythree = Cruise(name='Suez Canal', region='Greece', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719112850421_550X270.jpg', description_short="Take a trip to paradise in glorious Greece. The Greek islands are breathtaking, with idyllic beaches, pretty white-washed houses and atmospheric tavernas. In Athens you'll find awe-inspiring ancient wonders while for fun nightlife, head to Mykonos or Corfu.", description_long="The sight of spectacular Santorini will take your breath away. Be spellbound by sun-kissed beaches, cobalt seas, dazzling white houses, bright blue domes and dramatic volcanic mountains. Wander in lovely villages with narrow streets and winding steps, tasting a meze, Greek wine or pastry along the way. Secluded coves, hot springs and ancient settlements only increase the charms of this stunning island.", categories=[europe], ship=jewel_of_the_seas)

    cruisethirtyfour = Cruise(name='Mediterranean Venice', region='Montenegro', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170720053014449_550X270.jpg', description_short="Prepare to fall in love with breathtaking Montenegro. There are towering mountains, beautiful bays and clear Adriatic waters here, where you can hike, sail and scuba dive. In stunning Kotor, the atmospheric cafes, shops and alleyways of the medieval Old Town are a must.", description_long="Explore the ancient ramparts of this fabulous medieval city for some breath-taking views over the Adriatic. With its stunning mountains and World Heritage Site status, Kotor is a hidden gem. Savour delicious local specialities such as seafood, cured meats and pastries in the fascinating Old Town or swim, snorkel and kayak in the sapphire seas. For bird watchers, pelicans and flamingos are some of Montenegro’s other hidden treasures.", categories=[mediterranean], ship=jewel_of_the_seas)

    cruisethirtyfive = Cruise(name='Paris & Bilbao', region='France', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719112433505_550X270.jpg', description_short="You'll be charmed by La Belle France, where fine cuisine, famous fashion, iconic sights and a relaxed way of life combine to make holiday heaven. Hit the designer shops and exclusive restaurants of Paris or Provence or strut your stuff in chic Nice or Cannes.", description_long="Dabble in modern art at the fabulous Musée d’Orsay, visit glorious Versailles or take in iconic sights such as the Paris Opera, Notre Dame, the Arc de Triomphe and the Eiffel Tower. Explore Paris’ colourful districts on a walking tour of the cafés, boulevards and parks or shop for chic haute couture on Rue du Faubourg St Honoré. The D-Day beaches of Normandy also provide an unforgettable experience.", categories=[mediterranean], ship=anthem_of_the_seas)

    cruisethirtysix = Cruise(name='Greece & Croatia', region='Croatia', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719102824467_550X270.jpg', description_short="Croatia is a dream destination, with its stunning coastline and vibrant cultural life. In Dubrovnik, enjoy incredible views and cool clubs and bars. You'll love Split's Diocletian's Palace and the pretty countryside around Zadar, where exploring is a delight.", description_long="Walk the narrow streets and imagine life in the 4th century AD at magnificent Diocletian's Palace, an ancient palace built by the Roman emperor Diocletian that still forms half the old town of Split. Explore the buzzing bars, shops and restaurants that line the ancient walls, marvel at the town’s stunning coastal setting on a boat trip or scenic flight or splash in the gushing waterfalls in the Krka National Park.", categories=[mediterranean], ship=rhapsody_of_the_seas)

    cruisethirtyseven = Cruise(name='Western Mediterranean', region='Italy', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170719114106792_550X270.jpg', description_short="Impeccable style, divine cuisine, exquisite architecture - you'll be captivated by unmissable Italy. Explore the stunning art treasures of Florence, the romantic canals of Venice, the glorious monuments of Rome and Sicily's sizzling volcano - unforgettable.", description_long="Smile – you’re in unmissable Italy. Whizz on a zip-line over a 16th-century reservoir or hike around the rim of scary Mount Vesuvius. Sample Limoncello liqueur, salami or fresh mozzarella and explore dramatic Pompeii and stunning Sorrento. In Naples, discover the Royal Palace, the San Carlo Opera House and the Duomo, the city’s Cathedral.", categories=[mediterranean], ship=oasis_of_the_seas)

    cruisethirtyeight = Cruise(name='Qatar, Bahrain & The UAE', region='Bahrain', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20180424044527670_550X270.jpg', description_short="Walk the ancient walls of Bahrain Fort or shop for perfumes in the Manama Souq. Manama has skyscrapers and malls too, plus treasures like the National Museum. Visit the Formula 1 racetrack, explore the A’Ali Burial Mounds, spot oryx at Al Areen Wildlife Park or try pearl collecting at Dar Island.", description_long="Haggle for pearls, perfumes and spices in the colourful Bab al-Bahrain bazaar. Marvel at the exquisite interiors at Al Fateh Mosque or delve into ancient Dilmun history at the Bahrain National Museum. Bahrain Fort will take your breath away with its night-time illuminations while the Formula 1 racetrack and Al Dar Island beach will tempt you with pleasures of a modern kind.", categories=[middleeast], ship=jewel_of_the_seas)

    cruisethirtynine = Cruise(name='Ultimate Arabian Coast', region='Oman', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20180424031659610_550X270.jpg', description_short="Explore Oman’s beautiful coastline, looking out for dolphins, turtles and birds. Admire its stunning architecture, such as the Sultan Qaboos Grand Mosque, National Museum and Muscat’s old town. You’ll be inspired by heart-stirring landscapes too, at Wadi Bani Khalid, Khasab Beach and Sharqiya Sands.", description_long="Be wow’ed by the intricate opulence of the Sultan Qaboos Grand Mosque or the stunning new Royal Opera House. Explore Muscat’s Oman Oil and Gas Exhibition Centre for an understanding of oil in the Middle East or be tempted by exotic fragrances at the Amouage Perfume Factory. Explore the Muttrah Souq, one of the the oldest marketplaces in Muscat, or the Muttrah Corniche, a lovely waterfront promenade with mosques, street art and lovely views.", categories=[middleeast], ship=jewel_of_the_seas)

    cruiseforty = Cruise(name='Ultimate Arabian Coast', region='Qatar', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20180424032030321_550X270.jpg', description_short="In Souq Waqif, shop for oud and embroidered Qatari dress. Admire the hooded birds in the Falcon Souq and the Arabian horses in their stables. Be inspired by Doha’s Museum of Islamic Art or its impressive waterfront promenade. For thrills, try quad biking or camel riding in the desert.", description_long="Arabian horses, hooded falcons, the heady smell of incense in the souq – Qatar is an adventure in the exotic. Be wowed by Doha’s futuristic skyline along the waterfront Corniche, watching dhows bobbing on the water and families out for a stroll. Marvel at the exquisite treasures in the Museum of Islamic Art or head out of the city for sizzling sunsets over desert sands.", categories=[middleeast], ship=jewel_of_the_seas)

    cruisefortyone = Cruise(name='Oman & The UAE Holiday', region='United Arab Emirates', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20180423181724177_550X270.jpg', description_short="Daring Dubai will take your breath away. Have the time of your life in this sun-kissed playground in the UAE, full of mind-blowing skyscrapers, glittering malls, fun-packed theme parks and dazzling museums. For some down time, laze on the beach or stargaze under the desert sky.", description_long="Sand skiing, dune bashing and camel rides are some of the desert adventures on offer in amazing Abu Dhabi, where futuristic skyscrapers sit alongside mosques, museums and bazaars. Visit a falcon hospital, enjoy the world’s largest indoor theme park at Ferrari World or take high tea in an opulent hotel. Marvel at the largest Persian carpet in the world at the spectacular Sheikh Zayed Grand Mosque.", categories=[middleeast], ship=jewel_of_the_seas)

    cruisefortytwo = Cruise(name='Alaska Getaway', region='Alaska', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808104230944_550X270.jpg', description_short="Spot bears, bald eagles, whales, seals, wolves and sea otters in amazing Alaska. Soar above glaciers in a helicopter, admire breath-taking views from a gondola, run with huskies or learn about Native American cultures in this awe-inspiring wilderness.", description_long="One of Alaska’s most stunning coastal towns, Sitka has both Russian and American influences and is home to the Tlingit people. Find out about Tlingit culture at the Sitka National Historical Park or enjoy traditional dance and storytelling throughout the summer months. Take to the seas for fishing or whale spotting expeditions or discover the breath-taking bays and inlets on a boat or kayak trip.", categories=[northamerica], ship=serenade_of_the_seas)

    cruisefortythree = Cruise(name='Canada & New England', region='Canada', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808104510049_550X270.jpg', description_short="Vancouver is blessed with sea, mountains, beaches and breath-taking views. Enjoy nature and culture in this happening city, from the buzz of Granville Island to fun-packed Stanley Park. See another side of Canada in Victoria's lovely gardens or in romantic Old Quebec.", description_long="Browse the tempting stalls at the City Market, whose roof resembles the upturned keel of a ship. Be blown away by the amazing Reversing Rapids, where the Bay of Fundy’s high tides collide in spectacular fashion with the St. John River, or fly over the rapids on a zip-line. Check out the fascinating New Brunswick Museum for its Hall of Great Whales or try Nordic walking, geocaching, kayaking and mountain biking at Rockwood Park.", categories=[northamerica], ship=adventure_of_the_seas)

    cruisefortyfour = Cruise(name='Hawaii', region='Hawaii', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170808104718655_550X270.jpg', description_short="Explore the dramatic scenery of Hawaii, with its lush rainforests, rich marine life and awesome waves. Find out about the attack on Pearl Harbor in Honolulu and hit the shops in bustling Waikiki. In Lahaina you can stand on top of a dormant volcano - just amazing.", description_long="Be wow’ed by a helicopter tour, a great way to see the lush tropical landscape of Kauai, one of the smaller Hawaiian islands. Discover the Napali Coast, where Jurassic Park was filmed, or Wailua Falls, which served as the backdrop for the television series Fantasy Island. Relax on an idyllic river boat trip to the Fern Grotto or head to Kalapaki Beach for swimming, surfing, snorkelling or shopping.", categories=[northamerica], ship=radiance_of_the_seas)

    cruisefortyfive = Cruise(name='Norwegian Fjords', region='Norway', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170720053206009_550X270.jpg', description_short="Marvel at the spectacular sights of Norway, from magnificent fjords and glaciers to the awe-inspiring Northern Lights and Midnight Sun. You'll adore the art and Viking heritage of Oslo, Bergen's buzzing music scene and Alesund's fairytale charm.", description_long="Wonder at one of the world’s largest cannons, built by the Germans in WW2, or tour the former Gestapo HQ. Play pirates at the Abra Havn Pirate Village or explore 400-year-old houses at the open-air Folk Museum. There’s a fabulous zoo and amusement park for kids too plus a town beach. If you prefer beautiful scenery, the rocky coastline, stunning inlets and sparkling seas around Kristiansand will take your breath away.", categories=[scandinavia], ship=serenade_of_the_seas)

    cruisefortysix = Cruise(name='South Pacific & Fiji', region='Fiji', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170809070334615_550X270.jpg', description_short="Explore Lautoka's Sugar Mill, Hare Krishna Temple and Botanical Gardens for fascinating insights into Fijian life. In Suva you can unwind at a stunning beach report or sample exotic fruits in the markets. Don't miss Fijian rituals such as fire walking and kava drinking.", description_long="Relax in thermal mud pools near Lautoka, the second largest city in Fiji, or fly through the tropical jungle on a giant zip line. Sail to idyllic Tivua Island, lounge on white sand beaches under swaying palms or snorkel in the warm waters and emerald seas. Delight the senses at the South Sea Orchid Garden or visit the largest sugar mill in the South Pacific. Discover exotic fruit and vegetables at Lautoka Market.", categories=[southpacific], ship=voyager_of_the_seas)

    cruisefortyseven = Cruise(name='Transpacific', region='French Polynesia', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170809070504566_550X270.jpg', description_short="Snorkel with sharks and stingrays around Bora Bora's coral reefs or enjoy swimming in idyllic lagoons. See stunning views of Moorea's volcanic peaks or explore the lush interior by 4x4. Give in to temptation in Tahiti, where you'll find exquisite black pearls.", description_long="Bask on silky unspoilt beaches of endless white sand and gaze at sparkling clear blue waters filled with colourful fish – you are truly in heaven. Explore the dramatic mountain interior by helicopter or buy pearls and Polynesian arts and crafts in the shops and markets at Vaitape.", categories=[southpacific], ship=ovation_of_the_seas)

    cruisefortyeight = Cruise(name='South Pacific', region='Loyalty Islands', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170809070558909_550X270.jpg', description_short="Relaxation is the key to Lifou, the largest of the Loyalty Islands in New Caledonia. Bask in the friendly welcome and enjoy stunning beaches and balmy tropical seas. Take in the spectacular views from Notre Dame de Lourdes Chapel or visit a local vanilla plantation.", description_long="Relaxation is the key to Lifou, the largest of New Caledonia’s Loyalty Islands in the South Pacific, and a French overseas territory. Bask in the warmth of a friendly welcome, where local customs and traditions are evident all around. Enjoy balmy tropical seas, plus stunning beaches and fascinating caves. To gain insight into island life, visit Notre Dame de Lourdes Chapel or fragrant vanilla plantations.", categories=[southpacific], ship=serenade_of_the_seas)

    cruisefortynine = Cruise(name='South Pacific', region='New Caledonia', image='https://www.royalcaribbean.co.uk/assets/images/searchimages/2332.jpg', description_short="There's unbelievable beauty on the Isle of Pines, where you can spot spectacular marine life such as sea turtles and dolphins. In Noumea you can enjoy stunning beaches and popular water sports while in Mare look out for giant manta rays and rare dugongs.", description_long="Explore the startling architecture of the Jean-Marie Tjibaou Cultural Centre on the island of Grand Terre in New Caledonia, which celebrates local Kanak culture. There are French influences in Noumea too, in the colonial architecture and in the shops, bars and restaurants. Enjoy stunning beaches and popular water sports and visit the Aquarium des Lagons to learn more about local marine life and conservation.", categories=[southpacific], ship=radiance_of_the_seas)

    cruisefifty = Cruise(name='South Pacific', region='Vanuatu', image='https://www.royalcaribbean.co.uk/assets/images/destinations/country/hero_20170809070812702_550X270.jpg', description_short="On Vanuatu's 80 islands you'll find idyllic beaches, cascading waterfalls and fiery volcanoes. Enjoy perfect snorkeling around the stunning coral reefs at Champagne Bay and Mystery Island. In Port Vila, learn about traditional customs and shop for tempting souvenirs.", description_long="Relax under the palm trees on this paradise island, formerly used as an Allied landing strip during WW2. The turquoise waters and stunning coral reefs make it perfect for water sports such as snorkelling, paddle boarding or swimming or for exploring the rich marine life via glass bottomed boat. Be tempted by local crafts and souvenirs too on this lovely South Pacific island, where a friendly welcome awaits.", categories=[southpacific], ship=radiance_of_the_seas)



    db.commit()
